name: Build XML Tool for Windows x64

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build for Windows x64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.x"

      - name: Build binary
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          echo "Building for Windows x64"
          mkdir -p dist/windows-amd64
          go build -o dist/windows-amd64/xml-tool.exe ./go/xml-tool/main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: xml-tool-windows-amd64
          path: dist/windows-amd64/
