name: Build XML Tool

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build for Multiple Platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, darwin, linux]
        arch: [amd64, 386]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.x"

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          mkdir -p dist/${{ matrix.os }}-${{ matrix.arch }}
          go build -o dist/${{ matrix.os }}-${{ matrix.arch }}/xml-tool${{ matrix.os == 'windows' && '.exe' || '' }} tgfc/go/xml-tool/main.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xml-tool-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/${{ matrix.os }}-${{ matrix.arch }}/
