name: Build and Release XML Tool for Windows x64

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and Release for Windows x64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.x"

      - name: Build binary
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          echo "Building for Windows x64"
          mkdir -p dist/windows-amd64
          go build -o dist/windows-amd64/xml-tool.exe ./go/xml-tool/main.go

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "XML Tool Windows x64 v${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/windows-amd64/xml-tool.exe
          asset_name: xml-tool.exe
          asset_content_type: application/octet-stream
